name: social_mate
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  file_picker: ^10.3.8
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^20.1.0
  flutter_localization: ^0.3.3
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  google_sign_in: ^7.2.0
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  persistent_bottom_nav_bar_v2: ^6.2.0
  skeletonizer: ^2.1.2
  supabase_flutter: ^2.12.0
  timeago: ^3.7.1
  video_player: ^2.10.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
flutter_intl:
  enabled: true
